name: Cypress Console tests -- live environment

# This workflow runs using provided url

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Url'
        required: true
        type: string

jobs:
  cypress-run:
    name: Run Cypress Trading tests -- live environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
        node-version: 16

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          project: ./apps/trading-e2e
          config: baseUrl=${{ github.event.inputs.url }}
          env: grepTags=@live
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
