name: Generate tranches

# on:
#   schedule:
#     - cron: '0 8 * * *'

on:
  push:

jobs:
  master:
    name: Generate Queries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.VEGA_CI_BOT_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Use Node.js 16
        id: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
      - name: Install root dependencies
        run: yarn install
      - name: Generate queries
        run: node ./scripts/get-tranches.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update tranches'
          commit_options: '--no-verify --signoff'
          skip_fetch: true
          skip_checkout: true
        env:
          GITHUB_TOKEN: ${{ secrets.VEGA_CI_BOT_GITHUB_TOKEN }}
